name: Build Windows Exe

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Updated to a stable version for Windows

    - name: Install Dependencies
      run: |
        pip install pyinstaller watchdog pypdf pystray pillow customtkinter packaging

    - name: Build with PyInstaller
      run: |
        # Build command with GUI imports
        pyinstaller --noconsole --onefile --hidden-import=pypdf --hidden-import=PIL --hidden-import=Pillow --hidden-import=pystray --hidden-import=customtkinter --name "SmartSort" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartSort-Windows-Exe
        path: dist/SmartSort.exe
